In [1]:
import numpy as np
from sklearn import datasets
from sklearn import preprocessing

#1.Загрузите выборку Boston с помощью функции sklearn.datasets.load_boston(). 
#Результатом вызова данной функции является объект, у которого признаки записаны в поле data,
#а целевой вектор — в поле target.
bost=datasets.load_boston()

In [2]:
bost.data.shape, bost.target.shape
# 'feature_names': array(['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX', 'PTRATIO', 'B', 'LSTAT'], 
#dtype='<U7'),

((506, 13), (506,))

In [3]:
#iris = datasets.load_iris()
#iris
#iris.data.shape, iris.target.shape
#for x in bost.data.shape:
#    print (x)
bost.data[1]

array([2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
       6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
       1.7800e+01, 3.9690e+02, 9.1400e+00])

In [4]:
# 2. Приведите признаки в выборке к одному масштабу при помощи функции sklearn.preprocessing.scale.
X= preprocessing.scale(bost.data)

In [5]:
X[1]

array([-0.41526932, -0.48772236, -0.59338101, -0.27259857, -0.74026221,
        0.19427445,  0.36716642,  0.55715988, -0.8678825 , -0.98732948,
       -0.30309415,  0.44105193, -0.49243937])

In [6]:
# 3. Переберите разные варианты параметра метрики p по сетке от 1 до 10 с таким шагом, 
# чтобы всего было протестировано 200 вариантов (используйте функцию numpy.linspace). 

In [7]:
p_range = np.linspace(1,10,200)
#for p in p_range:
#    print (p)

In [8]:
# Используйте KNeighborsRegressor с n_neighbors=5 и weights='distance' 
# — данный параметр добавляет в алгоритм веса, зависящие от расстояния до ближайших соседей. 

In [57]:
from sklearn.neighbors import KNeighborsRegressor
#KNeighborsRegressor(n_neighbors=5, weights=’uniform’, algorithm=’auto’, leaf_size=30, p=2, metric=’minkowski’, metric_params=None, n_jobs=1, **kwargs)[source]¶
p_val=2
neigh = KNeighborsRegressor(n_neighbors=5, weights='distance',p=p_val)
neigh.fit(X,bost.target)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='distance')

In [58]:
# Качество оценивайте, как и в предыдущем задании, с помощью кросс-валидации 
#по 5 блокам с random_state = 42, не забудьте включить перемешивание выборки (shuffle=True).
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
print (kf)
for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = bost.target[train_index], bost.target[test_index]

KFold(n_splits=5, random_state=42, shuffle=True)


In [59]:
# В качестве метрики качества используйте среднеквадратичную ошибку 
#(параметр scoring='mean_squared_error' у cross_val_score; 
# при использовании библиотеки scikit-learn версии 0.18.1 и выше 
# необходимо указывать scoring='neg_mean_squared_error'). 
from sklearn.model_selection import cross_val_score
scores = cross_val_score(neigh,X,bost.target.ravel(),cv=kf,scoring='neg_mean_squared_error')

In [71]:
print("Accuracy: %0.16f (+/- %0.2f);" % (scores.mean(), scores.std() * 2))

Accuracy: -17.3366378842596696 (+/- 5.13);


In [61]:
scores

array([-19.14917772, -13.68282099, -20.87062784, -15.41202669,
       -17.56853618])

In [62]:
int(max(scores))

-13

In [63]:
max(scores)

-13.68282099131146

In [68]:
sum(scores) / len(scores)

-17.33663788425967

In [65]:
#loop
list_optim = []
for p_val1 in p_range:
    neigh = KNeighborsRegressor(n_neighbors=5, weights='distance',p=p_val1)
    neigh.fit(X,bost.target)
    scores1 = cross_val_score(neigh,X,bost.target,cv=kf,scoring='neg_mean_squared_error')
    list_optim.append((p_val1,max(scores1),scores1.mean(),scores1.std()))
    neigh = 0

In [66]:
for x in list_optim:
    print ("Accuracy[%0.1f]:%0.6f , %0.6f , %0.3f" % (x[0],x[1],x[2],x[3]))

Accuracy[1.0]:-11.878542 , -16.050209 , 3.310
Accuracy[1.0]:-11.996570 , -16.404081 , 3.501
Accuracy[1.1]:-11.844383 , -16.367229 , 3.469
Accuracy[1.1]:-11.836924 , -16.442539 , 3.427
Accuracy[1.2]:-11.876076 , -16.455281 , 3.396
Accuracy[1.2]:-12.035631 , -16.506563 , 3.390
Accuracy[1.3]:-12.019038 , -16.616752 , 3.352
Accuracy[1.3]:-12.591107 , -16.801912 , 3.081
Accuracy[1.4]:-12.601727 , -16.843957 , 3.038
Accuracy[1.4]:-12.581176 , -17.094611 , 3.152
Accuracy[1.5]:-12.897805 , -17.120015 , 3.149
Accuracy[1.5]:-12.932248 , -16.951350 , 2.960
Accuracy[1.5]:-13.312835 , -17.088927 , 2.883
Accuracy[1.6]:-13.383402 , -16.791080 , 2.648
Accuracy[1.6]:-13.917517 , -16.970884 , 2.602
Accuracy[1.7]:-13.949629 , -17.006164 , 2.347
Accuracy[1.7]:-14.072326 , -17.154255 , 2.418
Accuracy[1.8]:-13.870069 , -17.171595 , 2.447
Accuracy[1.8]:-13.829324 , -17.200173 , 2.506
Accuracy[1.9]:-13.584011 , -17.319404 , 2.734
Accuracy[1.9]:-13.520177 , -17.410890 , 2.753
Accuracy[1.9]:-13.672092 , -17.382

In [67]:
a=np.array(list_optim)
np.amin(a, axis=0)

array([  1.        , -19.70222365, -21.10924301,   1.17689929])

In [ ]:
# tried 9.5 - maximum of average, wrong:
# rec: Проверьте, верно ли вы находите значение функционала качества