In [8]:
import numpy as np
import pandas 
from sklearn.svm import SVC

In [15]:
# SVM =  Support Vector Machine 
# SVC = Support Vector Classification 
# 1. Загрузите выборку из файла svm-data.csv. 
#В нем записана двумерная выборка (целевая переменная указана в первом столбце, признаки — во втором и третьем).
data = pandas.read_csv('svm-data.csv', header=None)

In [16]:
X=np.array(data.loc[:,1:])
y=np.array(data.loc[:,0])

In [24]:
y

array([0., 1., 0., 0., 0., 1., 0., 1., 0., 1.])

In [17]:
# 2. Обучите классификатор с линейным ядром, параметром C = 100000 и random_state=241. 
# Такое значение параметра нужно использовать, чтобы убедиться, что SVM работает с выборкой как с линейно разделимой. 
# При более низких значениях параметра алгоритм будет настраиваться с учетом слагаемого в функционале, 
# штрафующего за маленькие отступы, из-за чего результат может не совпасть с решением классической задачи SVM 
# для линейно разделимой выборки.
#SVC(C=1.0, kernel=’rbf’, degree=3, gamma=’auto’, coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape=’ovr’, random_state=None)[source]¶
clf = SVC(C = 100000,kernel='linear',random_state=241)
clf.fit(X, y) 

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=241, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
# 3. Найдите номера объектов, которые являются опорными (нумерация с единицы). 
# Они будут являться ответом на задание. Обратите внимание, что в качестве ответа нужно привести
# номера объектов в возрастающем порядке через запятую или пробел. Нумерация начинается с 1.
#clf.get_params()
#clf.predict(X)
clf.support_

array([3, 4, 9], dtype=int32)

In [30]:
clf.support_vectors_

array([[0.98, 0.68],
       [0.48, 0.39],
       [0.53, 0.53]])